// ===== Dental Pin — Mock Data =====

// بيانات وهمية للعرض أثناء التطوير

export const mockDoctor = {
  id: '1',
  name: 'د. أحمد محمد',
  specialization: 'طبيب أسنان',
  phone: '01012345678',
  workingHours: { start: '09:00', end: '21:00' },
  workingDays: [0, 1, 2, 3, 4, 5],
};

export const mockPatients = [
  {
    id: '1',
    name: 'محمد أحمد علي',
    phone: '01098765432',
    date_of_birth: '1990-05-15',
    gender: 'male',
    address: 'المعادي، القاهرة',
    notes: 'يعاني من حساسية البنسلين',
    created_at: '2026-08-01T10:00:00',
    lastVisit: '2026-09-07',
    nextAppointment: '2026-09-09',
    status: 'active',
  },
  {
    id: '2',
    name: 'فاطمة حسن',
    phone: '01123456789',
    date_of_birth: '1985-11-22',
    gender: 'female',
    address: 'مدينة نصر، القاهرة',
    notes: '',
    created_at: '2026-07-15T14:30:00',
    lastVisit: '2026-09-05',
    nextAppointment: '2026-09-10',
    status: 'active',
  },
  {
    id: '3',
    name: 'أحمد سعيد',
    phone: '01234567890',
    date_of_birth: '1995-03-08',
    gender: 'male',
    address: 'الدقي، الجيزة',
    notes: 'مريض سكر',
    created_at: '2026-06-20T09:00:00',
    lastVisit: '2026-08-28',
    nextAppointment: null,
    status: 'active',
  },
  {
    id: '4',
    name: 'سارة محمود',
    phone: '01056789012',
    date_of_birth: '2000-07-30',
    gender: 'female',
    address: 'المهندسين، الجيزة',
    notes: '',
    created_at: '2026-09-01T11:00:00',
    lastVisit: null,
    nextAppointment: '2026-09-09',
    status: 'new',
  },
  {
    id: '5',
    name: 'عمر خالد',
    phone: '01187654321',
    date_of_birth: '1988-12-10',
    gender: 'male',
    address: 'الزمالك، القاهرة',
    notes: '',
    created_at: '2026-08-10T16:00:00',
    lastVisit: '2026-09-03',
    nextAppointment: '2026-09-11',
    status: 'active',
  },
  {
    id: '6',
    name: 'نور الدين حسين',
    phone: '01298765432',
    date_of_birth: '1992-01-25',
    gender: 'male',
    address: 'حلوان، القاهرة',
    notes: 'يحتاج تقويم',
    created_at: '2026-05-05T08:30:00',
    lastVisit: '2026-08-15',
    nextAppointment: null,
    status: 'active',
  },
  {
    id: '7',
    name: 'هدى عبدالرحمن',
    phone: '01067890123',
    date_of_birth: '1978-09-18',
    gender: 'female',
    address: 'شبرا، القاهرة',
    notes: '',
    created_at: '2026-04-12T12:00:00',
    lastVisit: '2026-07-20',
    nextAppointment: null,
    status: 'inactive',
  },
  {
    id: '8',
    name: 'كريم عبدالله',
    phone: '01156789012',
    date_of_birth: '2002-04-05',
    gender: 'male',
    address: '6 أكتوبر، الجيزة',
    notes: '',
    created_at: '2026-09-05T10:00:00',
    lastVisit: null,
    nextAppointment: '2026-09-09',
    status: 'new',
  },
  {
    id: '9',
    name: 'ياسمين أحمد',
    phone: '01078901234',
    date_of_birth: '1996-06-12',
    gender: 'female',
    address: 'التجمع الخامس، القاهرة',
    notes: '',
    created_at: '2026-08-20T15:00:00',
    lastVisit: '2026-09-08',
    nextAppointment: '2026-09-12',
    status: 'active',
  },
  {
    id: '10',
    name: 'مصطفى إبراهيم',
    phone: '01189012345',
    date_of_birth: '1982-02-28',
    gender: 'male',
    address: 'العباسية، القاهرة',
    notes: 'ضغط مرتفع',
    created_at: '2026-03-01T09:30:00',
    lastVisit: '2026-09-06',
    nextAppointment: null,
    status: 'active',
  },
];

const today = new Date();
const todayStr = `${today.getFullYear()}-${(today.getMonth() + 1).toString().padStart(2, '0')}-${today.getDate().toString().padStart(2, '0')}`;

export const mockAppointments = [
  {
    id: '1',
    patient_id: '1',
    patient_name: 'محمد أحمد علي',
    patient_phone: '01098765432',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '1',
    service_name: 'كشف',
    appointment_date: todayStr,
    appointment_time: '09:00',
    status: 'completed',
    notes: '',
    source: 'admin',
    checked_in_at: `${todayStr}T08:55:00`,
    checked_out_at: `${todayStr}T09:25:00`,
    created_at: '2026-09-07T10:00:00',
  },
  {
    id: '2',
    patient_id: '2',
    patient_name: 'فاطمة حسن',
    patient_phone: '01123456789',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '2',
    service_name: 'تنظيف أسنان',
    appointment_date: todayStr,
    appointment_time: '09:30',
    status: 'completed',
    notes: '',
    source: 'admin',
    checked_in_at: `${todayStr}T09:28:00`,
    checked_out_at: `${todayStr}T10:10:00`,
    created_at: '2026-09-06T14:30:00',
  },
  {
    id: '3',
    patient_id: '4',
    patient_name: 'سارة محمود',
    patient_phone: '01056789012',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '3',
    service_name: 'حشو',
    appointment_date: todayStr,
    appointment_time: '10:30',
    status: 'in_treatment',
    notes: 'حشو ضرس علوي',
    source: 'online',
    checked_in_at: `${todayStr}T10:25:00`,
    checked_out_at: null,
    created_at: '2026-09-08T11:00:00',
  },
  {
    id: '4',
    patient_id: '8',
    patient_name: 'كريم عبدالله',
    patient_phone: '01156789012',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '5',
    service_name: 'علاج عصب',
    appointment_date: todayStr,
    appointment_time: '11:30',
    status: 'arrived',
    notes: '',
    source: 'admin',
    checked_in_at: `${todayStr}T11:20:00`,
    checked_out_at: null,
    created_at: '2026-09-05T10:00:00',
  },
  {
    id: '5',
    patient_id: '5',
    patient_name: 'عمر خالد',
    patient_phone: '01187654321',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '1',
    service_name: 'كشف',
    appointment_date: todayStr,
    appointment_time: '13:00',
    status: 'confirmed',
    notes: '',
    source: 'admin',
    checked_in_at: null,
    checked_out_at: null,
    created_at: '2026-09-07T16:00:00',
  },
  {
    id: '6',
    patient_id: '9',
    patient_name: 'ياسمين أحمد',
    patient_phone: '01078901234',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '4',
    service_name: 'خلع',
    appointment_date: todayStr,
    appointment_time: '14:00',
    status: 'pending',
    notes: 'خلع ضرس العقل',
    source: 'online',
    checked_in_at: null,
    checked_out_at: null,
    created_at: '2026-09-08T20:00:00',
  },
  {
    id: '7',
    patient_id: '3',
    patient_name: 'أحمد سعيد',
    patient_phone: '01234567890',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '6',
    service_name: 'تركيبات',
    appointment_date: todayStr,
    appointment_time: '15:30',
    status: 'pending',
    notes: '',
    source: 'admin',
    checked_in_at: null,
    checked_out_at: null,
    created_at: '2026-09-04T09:00:00',
  },
  {
    id: '8',
    patient_id: '10',
    patient_name: 'مصطفى إبراهيم',
    patient_phone: '01189012345',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '2',
    service_name: 'تنظيف أسنان',
    appointment_date: todayStr,
    appointment_time: '16:30',
    status: 'cancelled',
    notes: 'المريض اعتذر',
    source: 'admin',
    checked_in_at: null,
    checked_out_at: null,
    created_at: '2026-09-06T12:00:00',
  },
  // مواعيد أيام أخرى
  {
    id: '9',
    patient_id: '5',
    patient_name: 'عمر خالد',
    patient_phone: '01187654321',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '7',
    service_name: 'تقويم أسنان',
    appointment_date: (() => { const d = new Date(); d.setDate(d.getDate() + 1); return `${d.getFullYear()}-${(d.getMonth()+1).toString().padStart(2,'0')}-${d.getDate().toString().padStart(2,'0')}`; })(),
    appointment_time: '10:00',
    status: 'confirmed',
    notes: '',
    source: 'admin',
    checked_in_at: null,
    checked_out_at: null,
    created_at: '2026-09-07T08:00:00',
  },
  {
    id: '10',
    patient_id: '2',
    patient_name: 'فاطمة حسن',
    patient_phone: '01123456789',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '8',
    service_name: 'تبييض أسنان',
    appointment_date: (() => { const d = new Date(); d.setDate(d.getDate() + 1); return `${d.getFullYear()}-${(d.getMonth()+1).toString().padStart(2,'0')}-${d.getDate().toString().padStart(2,'0')}`; })(),
    appointment_time: '14:00',
    status: 'pending',
    notes: '',
    source: 'online',
    checked_in_at: null,
    checked_out_at: null,
    created_at: '2026-09-08T18:00:00',
  },
  {
    id: '11',
    patient_id: '6',
    patient_name: 'نور الدين حسين',
    patient_phone: '01298765432',
    doctor_id: '1',
    doctor_name: 'د. أحمد محمد',
    service_id: '7',
    service_name: 'تقويم أسنان',
    appointment_date: (() => { const d = new Date(); d.setDate(d.getDate() + 2); return `${d.getFullYear()}-${(d.getMonth()+1).toString().padStart(2,'0')}-${d.getDate().toString().padStart(2,'0')}`; })(),
    appointment_time: '11:00',
    status: 'pending',
    notes: '',
    source: 'admin',
    checked_in_at: null,
    checked_out_at: null,
    created_at: '2026-09-06T10:00:00',
  },
];

export const mockNotifications = [
  {
    id: '1',
    type: 'new_booking',
    title: 'حجز جديد',
    message: 'تم استلام طلب حجز جديد من ياسمين أحمد — خلع ضرس العقل',
    is_read: false,
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: '2',
    type: 'upcoming',
    title: 'موعد قريب',
    message: 'لديك موعد قادم مع عمر خالد الساعة 1:00 م',
    is_read: false,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: '3',
    type: 'cancelled',
    title: 'إلغاء موعد',
    message: 'تم إلغاء موعد مصطفى إبراهيم — تنظيف أسنان',
    is_read: false,
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: '4',
    type: 'new_booking',
    title: 'حجز إلكتروني',
    message: 'تم استلام طلب حجز إلكتروني من سارة محمود — حشو',
    is_read: true,
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: '5',
    type: 'rescheduled',
    title: 'إعادة جدولة',
    message: 'تمت إعادة جدولة موعد فاطمة حسن إلى يوم الأربعاء',
    is_read: true,
    created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
  {
    id: '6',
    type: 'upcoming',
    title: 'موعد غداً',
    message: 'تذكير: لديك 3 مواعيد غداً',
    is_read: true,
    created_at: new Date(Date.now() - 72 * 3600000).toISOString(),
  },
];

// إحصائيات وهمية للتقارير
export const mockReportStats = {
  today: {
    totalAppointments: 8,
    completed: 2,
    cancelled: 1,
    noShow: 0,
    newPatients: 2,
    returningPatients: 6,
    revenue: 1050,
  },
  week: {
    totalAppointments: 35,
    completed: 22,
    cancelled: 4,
    noShow: 2,
    newPatients: 8,
    returningPatients: 27,
    revenue: 12500,
  },
  month: {
    totalAppointments: 142,
    completed: 98,
    cancelled: 15,
    noShow: 8,
    newPatients: 25,
    returningPatients: 117,
    revenue: 48000,
  },
};

// بيانات الرسم البياني
export const mockChartData = {
  labels: ['السبت', 'الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة'],
  completed: [5, 7, 4, 6, 3, 8, 0],
  cancelled: [1, 0, 2, 1, 0, 1, 0],
  noShow: [0, 1, 0, 1, 0, 0, 0],
};
